### ISSUE TITLE
Couldn't start on Windows

### ISSUE THREAD

**Issue by teta2k** [GameTheory-/mktool#2]
PS D:\Downloads\mktool-4.1\mktool> java -jar  .\mktool.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at Main.main(Main.java:10)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at unpack_repack_util.UnpackRepackUtil.getDir(UnpackRepackUtil.java:341)
        at unpack_repack_util.UnpackRepackUtil.<clinit>(UnpackRepackUtil.java:18)
        ... 1 more

PS D:\Downloads\mktool-4.1\mktool> java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)

**Comment by GameTheory-** [comment]
This tool is for Linux and does not run in Windows.
