### ISSUE TITLE
Error Java MKTOOL 4.1

### ISSUE THREAD

**Issue by marmmc** [GameTheory-/mktool#3]
Hello, Brother....

I m execute you mktool, exist error:

C:\Users\marmmc\Downloads\mktool-4.0\mktool>java -jar mktool.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at Main.main(Main.java:10)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 55
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
        at java.base/java.lang.String.substring(String.java:1907)
        at unpack_repack_util.UnpackRepackUtil.getDir(UnpackRepackUtil.java:340)
        at unpack_repack_util.UnpackRepackUtil.<clinit>(UnpackRepackUtil.java:18)
        ... 1 more
        
        
    What Solved?

**Comment by GameTheory-** [comment]
You're using Windows. This is for use on Linux only.
